### ISSUE TITLE
Review: AddRestaurants and EditRestaurants.

### ISSUE THREAD

**Issue by cammoore** [cammoore/campus-cravings#4]
(Delete all text in parentheses when filling out this template, including this text.)

## Review Branch

[review-4](https://github.com/cammoore/campus-cravings/tree/review-4)

## Files to review

* [AddRestaurants.jsx](https://github.com/cammoore/campus-cravings/blob/review-4/app/imports/ui/pages/AddRestaurants.jsx)
* [EditRestaurants.jsx](https://github.com/cammoore/campus-cravings/blob/review-4/app/imports/ui/pages/EditRestaurants.jsx)

## Checklists

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)

## Due date

9/6/2022

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414f22/morea/review/reading-idpm-review.html

**Comment by charlie-robison** [comment]
AddRestaurants.jsx:
L23: JS-05: The React class component should be converted into a React arrow function.

L8: REACT-03: The import statement imports the “Restaurant.jsx” file as “Restaurants” as the component which is not the original name of the file.

L23: REACT-09: The React class component can be turned into a React arrow function component since the component is stateless.

EditRestaurants.jsx:

L53: Design-05: The comment does not detail the correct props passed by saying a “Stuff document” is required when no prop called Stuff is passed.

L14: JS-05: The React class component should be converted into a React arrow function.

L67: REACT-06: “doc” should be defined as const and set to the database query before being returned in withTracker.

L14: REACT-09: The React class component can be turned into a React arrow function component since the component is stateless.

**Comment by cammoore** [comment]
## AddRestaurants.jsx

JS-08:
https://github.com/cammoore/campus-cravings/blob/93f575bece6c33635abf62ee1523a74af3ac1361/app/imports/ui/pages/AddRestaurants.jsx#L10
https://github.com/cammoore/campus-cravings/blob/93f575bece6c33635abf62ee1523a74af3ac1361/app/imports/ui/pages/AddRestaurants.jsx#L22
https://github.com/cammoore/campus-cravings/blob/93f575bece6c33635abf62ee1523a74af3ac1361/app/imports/ui/pages/AddRestaurants.jsx#L40
RE09:
https://github.com/cammoore/campus-cravings/blob/93f575bece6c33635abf62ee1523a74af3ac1361/app/imports/ui/pages/AddRestaurants.jsx#L23

Line 29: shouldn't directly insert into collection.

## EditRestaurants.jsx

JS-08: L13, 16, 24, 29, 53, 60
DE-03: L56 propTypes model is not used or set.

Line 19: should directly update collection.

**Comment by alvinedrada** [comment]
AddRestaurants.jsx
Design-05: Ensure comments are appropriate
line 22 Change document to restaurant

EditRestaurants.jsx
Design-05: Ensure comments are appropriate
line 13 Change document to restaurant
line 53, line 64 Change Stuff to restaurant
REACT-06: Define constants in withTracker()
line 67 define doc outside return {}

**Comment by charlie-robison** [comment]
## AddRestaurants.jsx
L23: JS-05: The React class component should be converted into a React arrow function.

L8: REACT-03: The import statement imports the “Restaurant.jsx” file as “Restaurants” as the component which is not the original name of the file.

L23: REACT-09: The React class component can be turned into a React arrow function component since the component is stateless.

## EditRestaurants.jsx
L53: Design-05: The comment does not detail the correct props passed by saying a “Stuff document” is required when no prop called Stuff is passed.

L14: JS-05: The React class component should be converted into a React arrow function.

L67: REACT-06: “doc” should be defined as const and set to the database query before being returned in withTracker.

L14: REACT-09: The React class component can be turned into a React arrow function component since the component is stateless.

**Comment by cathy-kim95** [comment]
EditRestraurants.jsx
- REACT-09: Line 14 Prefer functions vs. classes
- JS-08: /** comments

AddRestaurants.jsx
- REACT-09: Line 23 Prefer functions vs. classes
- JS-08: /** comments

**Comment by gbaik00** [comment]
AddRestaurants.jsx
L34: ‘Item added successfully’ should be ‘Restaurant added successfully’

EditRestaurants.jsx
L21: ‘Item updated successfully’ should be ‘Restaurant updated successfully’
L7, 54-57: Importing of PropTypes, usage unclear.
Unable to edit the Owner field that AddRestaurants has, what if ownership changes?

Both
Inconsistency in IDing TextFields, Grid, etc. (ADD L49-55, EDIT L37-43)
TextFields either do not have proper labeling to tell which is meant for what or the labeling inside said TextFields are not simple to read (example: ‘serviceDays’ instead of ‘Days in Service’.

**Comment by rfitzy21** [comment]
### **AddRestaurants.jsx**
L31 JS-05: Could utilize arrow function with truthy conditional
L25 JS-08:  comments feel unnecessary.



### **EditRestaurants.jsx**
L67, L68 REACT-06: should define constants in withTracker and return the shorthand.
L16 JS-08: comment feels unnecessary

**Comment by ethancheez** [comment]
# AddRestaurants.jsx:

L8: REACT-08: Imported “Restaurants” but file name is “Restaurant”

L14: REACT-09: Stateless component, change to function instead of class

L52, 53: JS-01: restaurant-field-days and restaurant-field-hours ID names inconsistent with serviceDays and serviceHours names

# EditRestaurants.jsx:

L9: REACT-08: Imported “Restaurants” but file name is “Restaurant”

L14: REACT-09: Stateless component, change to function instead of class

L53, 64: Comment is referencing “Stuffs” collection

**Comment by gailag** [comment]
Both: Uses class instead of function components

EditRestaurant.jsx: 
Comments are not consistent – uses /** and //. Should just stick to one.
Uses underscore (_id)

**Comment by ianbm** [comment]
AddRestaurants.jsx:
Line 23: REACT-09: Stateless component should be written as a function.

EditRestaurants.jsx:
Line 14: REACT-09: Stateless component should be written as a function.
Lines 53 and 64: DESIGN-05: Comments about stuff documents are irrelevant.

**Comment by ujjwalrg** [comment]
## EditRestaurants.jsx

### React Review

- **Line 20:** EditRestaurants(stateless component) uses class component instead of functional
- **Line 15:** Imported Component and filename don't match

### JavaScript Review

- **Line 46, 64:** Could've destructured this.props earlier for Line 46 and 64 to use.
- **Line 20:** EditRestaurants class component can be changed to functional component using the arrow function.

---

---

## AddRestaurants.jsx

### React Review

- **Line 23:** Uses class component(stateless component) instead of functional

### JavaScript Review

- **Line 36:** Could use {...data, owner} spread operator, the data destructuring in lines 32-33 is redundant.
- **Line 29:** AddRestaurants(stateless component) class component can be changed to functional component
  using the arrow function.

**Comment by tineriver** [comment]
AddRestaurants.jsx:
Line 11-18 : Define constants in withTracker().

EditRestaurants.jsx:
Page has no integration test

**Comment by michnotmeesh** [comment]
AddRestaurants:
REACT-03: Do not rename default exports. Line 8
REACT-09: Prefer functions vs. classes for stateless components.
Design-05: Ensure comments are appropriate.

**Comment by ghost** [comment]
EditResturants.jsx

DE-05: Ensure comments are appropriate.

L53: Comment references the stuffs collection when there is no stuffs collection. 
L64: Comment references the stuffs collection when there is not stuffs collection.

**Comment by ecadiena** [comment]
AddRestaurants.jsx and EditRestaurants.jsx
REACT-09: this component is stateless and should use arrow format instead of class

should use:
const AddRestaurants = () => {...}  
const EditRestaurants = () => {...}

**Comment by adamjparrilla** [comment]
AddRestaurant Page:
L8: REACT-01: Do not rename default exports with Restaurants from Restaurant

**Comment by devgav** [comment]
AddRestaurants:
line 31-37: Can refractor to be more simpler using ternary

Both:
React-09: should use functional component instead of class

**Comment by larissa-tsai** [comment]
AddRestaurants.jsx and EditRestaurants.jsx

- Arch-01: Obey file name conventions, File is not in camel case
- React-08 imported "Restaurant.jsx" as Restaurants
- React 09 Stateless component should be written as a function
- DE 05:  Appropriate comments, inconsistencies between formats /** or //

**Comment by tanner-ky** [comment]
AddRestaurants.jsx
- File doesn't use camel case
- class name doesn't use camel case
- L8: imports Restaurants from file names Restaurant

EditRestaurants.jsx
- File doesn't use camel case
- class name doesn't use camel case

**Comment by CrisJavier** [comment]
AddRestaurants.jsx
JS-08: no need for jsdoc comments for regular comments ie; L10, 22, 25, etc.

EditRestaurants.jsx
JS-08: Same as above, ie; L13, 16, 24

**Comment by William-Liang808** [comment]
AddRestaurants.jsx
line 31 - 36, can be shortened with ternary

EditRestaurants.jsx
line 53 - no stuff document

Both
files not camel case

**Comment by jwu0** [comment]
AddRestaurants.jsx
L8 React-03: Imported Restaurants when it should be Restaurants

EditRestaurants.jsx
L9: Imports restaurants when it should be restaurant
L53: comments from base stuffs template

**Comment by Thaneluna** [comment]
AddRestaurants.jsx
JS-03:
12-17
REACT-06:
42
REACT-08:
Line 23
EditRestaurants.jsx
REACT-08:
Line 14

**Comment by eric-song1773** [comment]
AddRestaurants.jsx

- React-09: Functional components can be used instead of class.
- React-03: In Line 8, "Restaurants" is imported, but the file name is "Restaurant"
- Line 30-37 could be shorten into how EditRestaurants.jsx handles swal errors.

EditRestaurants.jsx

- React-03: In Line 9, "Restaurants" is imported, but the file name is "Restaurant"
- React-09: Functional components can be used instead of class.
- Line 53 and Line 64 comment talks about "stuff"

**Comment by sle417** [comment]
AddRestaurants:
- Design-05: Ensure comments are descriptive and appropriate for method/function.

EditRestaurants:
- Design-03: Model proptype should be removed as it is not used.

**Comment by ghost** [comment]
AddRestaurants.jsx
JS-01: L42: use a more descriptive name than fRef
Design-07: L31 - L33: The submit function in the AddRestaurants file can use ternary operator as a shorthand for an if else statement

EditRestaurants.jsx
JS-08: L16: Unnecessary comment

**Comment by joshmcons** [comment]
AddRestaurants and EditRestaurants
Arch01 - Files are not camel cased

**Comment by kerensaa** [comment]
AddRestaurants.jsx
JS01:  Code line 42: could change the variable name fRef to something else to make it more intuitive.
JS05:  Code line 30: could implement the arrow function here with ternary operator as used in EditRestaurants.jsx

**Comment by adrianwtam** [comment]
AddRestaurant.jsx
L12-17: Schema is all using String data type. May cause an issue later down the line when people have false expectations of data type

Both: Not using camelCase

**Comment by Kobeyarai808** [comment]
AddRestraunts.jsx
L37: The brackets are not balanced. It is good for code readability to balance the brackets and parenthesis. 
L44 & 60: There are 4 spaces when the ESLint style says 2 spaces are the convention.

**Comment by Cole-House** [comment]
AddRestaurant.jsx
Line 34-35 (Design-02): indentation in else clause should be not the same level as else
EditRestaurant.jsx
Line 56 (Design-03): Prop type model is not used in code

**Comment by yongsungm** [comment]
AddRestaurants.jsx
Arch01 - File name does not use camel case.
JS01 - Line 42 - Variable fRef doesn't have a descriptive name.
JS08 Lines 10, 22, 25 shouldn't be commented with /**

EditRestaurant.jsx
JS08 Lines 13, 16, 24, 29, 53, 60 shouldn't be commented with /**
Lines 53, 64 comments mention "Stuff"

**Comment by magnusfarstad** [comment]
#### AddRestaurant.jsx
* R09 (L29): Component is stateless.
* ARCH01: File is in Pascal case, not camel case.
#### EditRestaurant.jsx
* ARCH01: File is in Pascal case, not camel case.
* (L53, L64): No 'stuff' in code.

**Comment by tkansaki** [comment]
AddRestaurants.jsx
-Coding standard dictates there be a newline at the end of the file

EditRestaurants.jsx
-remove references to 'stuff'
-Coding standard dictates there be a newline at the end of the file

Overall
-perhaps the datatypes of serviceDays and serviceHours could be modified. Just having strings can allow the user to write such information in any format, making it harder to process that data should the need arise. Also, who's to say that different days does not have different hours?

**Comment by zakgilbert** [comment]
### AddRestaurants
* Lines 11-18, Line 27, Line 29
    * **Design-08:** Wet code
        * Some repetitive language going on here... starting with the formSchehma, not sure but this might be the only way to implement, if not find a way to not repeat *name, address, image, serviceDays, serviceHours, and description* a bunch of times.
* Lines 11-18 
    * **Design-09**: Ensure reusable code is exported or made available in the appropriate place.
         * RestrauntsSchemea should be imported from the RestaurantsCollection, this Mistake is not made in EditResgstraunts.jsx
* Lines 25, 48
    * **JS-08**: Use JSDoc comments appropriately.
        * I feel that you would only want JSDoc comment tags at the top of the component, like on line 23. Nested comments should be inline.
* Line 28
    * **REACT-06**: Define constants in withTracker().
### EditRestaurants
* Lines 18 & 19
    * **Design-08** Wet code
        * Some repetitive language going on here starting with the formSchehma, no sure but this might be the only way to implement, if not find a way to not repeat *name, address, image, serviceDays, serviceHours, and description* four times.
* Line 11
    * **JS-01:** Name constructs appropriately.
        * I'm not sure what a bridge is.
* Lines 16, 24, 29, 53, 60
    * **JS-08:** Use JSDoc comments appropriately.
        * I feel that you would only want JSDoc comment tags at the top of the component. Nested comments should be inline.
* Line 18
    * **REACT-06:** Define constants in withTracker().
