### ISSUE TITLE
Review: Favorites.jsx and Footer.jsx

### ISSUE THREAD

**Issue by cammoore** [cammoore/campus-cravings#5]
## Overview

We are going to learn how to conduct an IDPM Review.

## Review Branch

[review-5](https://github.com/cammoore/campus-cravings/blob/review-5/)

## Files to review

* [Favorites.jsx](https://github.com/cammoore/campus-cravings/blob/review-5/app/imports/ui/components/Favorite.jsx)
* [Footer.jsx](https://github.com/cammoore/campus-cravings/blob/review-5/app/imports/ui/components/Footer.jsx)

## Checklists

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)

## Due date

1/23

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s23/morea/review/reading-idpm-review.html

**Comment by cammoore** [comment]
## Favorites.jsx

AR-01: Filename is Favorites while the component is named Favorite.
JS-08: L6, L27, L33 Don't use /** comments
RE-09: L7 Prefer arrow functions.
L9, 10: Why rename the props?
L34 Don't need the withRouter there are no <Link> elements.

## Footer.jsx

JS-08: L3 /** comment. Is the comment correct?
RE-09: L4 Prefer arrow functions
L6 Do we need this const? It is only used once.

**Comment by giorgio-tran** [comment]
### Favorite.jsx

L7: REACT-09: Use function since it’s a stateless component

L6: Comment doesn’t match content, talks about ListStuff when it’s supposed to be ‘Favorite’

L9, 17, 20: RestaurantInfo → restaurantInfo, upper camel case is reserved for React components

### Footer.jsx

L4: REACT-09: Use function since it’s a stateless component

**Comment by lsollis** [comment]
Footer.js, Line 4, REACT-09 prefer functions vs classes for static components
Footer.jsx, line 6 / Favorite.js lines 9 and 10, REACT-06 define constants in withTracker()

Favorite.js, Lines 9 and 10, REACT-04 destructure props in the component parameter
Favorite.js, Lines 6, comment is not accurate to function of Favorite component

**Comment by khirano7** [comment]
Favorite.jsx
- Design-05: L6: Comment talks about List Stuff, should be changed to talk about the Favorite component
- JS-01: L9: variable RestaurantInfo 
- JS-08: L6, L27, L33
- REACT-09: Favorite is a stateless component
 
Footer.jsx
- JS-08: L3
- REACT-09: Footer is a stateless component

**Comment by michnotmeesh** [comment]
Favorite.jsx
- Design-05: Ensure comments are appropriate. Line 6.

Footer.jsx
- React-09: Prefer functions vs classes for stateless components

**Comment by susankpma** [comment]
Favorites.jsx

- Design-03 and 05: lines 33-34: comment indicates using withRouter and Link. Link is not used, is withRouter necessary?
- Design-05. line 6: Comments on “Stuff” should relate to restaurant info
- JS-01. line 9: naming convention on const
- React-09. function instead of class

Footer.jsx

- Design line 6: put in the CSS
- React-09: function instead of class

**Comment by graquepo** [comment]
Favorites.jsx
- Architecture-01: Favorites file name but Favorite component name
- JavaScript-08: Uses /** for comments
- Design-05: Unnecessary comments

Footer.jsx
- Design-05: Comments were unnecessary
- React-09: Stateless component

**Comment by justinjandoc** [comment]
## Favorites.jsx
L6, 27, 33: JS-08: Comments are made with /** */ but are not in the style of JSDoc.
L7: REACT-09: This component is stateless, therefore replace the class with a function.
L9, 10: REACT-04: Destructure these props.
L9, 10: JS-01: RestaurantInfo and menuItemInfo do not have consistent casing.
L12 - 22: ESLINT-01: These lines have 2 extra indents (line 12 has 8 spaces, but 6 are expected).

## Footer.jsx
L3: JS-08: Comment is made with /** */ but is not in the style of JSDoc.
L4: REACT-09: This component is stateless, therefore replace the class with a function.
L8 - 16: ESLINT-01: These lines have 2 extra indents.

**Comment by KyoufuuN1K1** [comment]
Favorites.jsx:

AR-01:
 File name Favorites does not match class name
DE-05:
 Line 6 - comment line makes no sense; does not describe what the code actually does
JS-02:
 Line 9-10 variables RestaurantInfo and MenuItemInfo have inconsistent casing. Pick one.
RE-09:
 Favorite is a stateless component
RE-10:
 Line 34 WithRouter seems unnecessary.

Footer.jsx:

RE-09:
 4 - Stateless component. Use function instead of class.

**Comment by timothyro** [comment]
Favorites.jsx
- JS-01: L9 const RestaurantInfo …: first letter of variable could be lowercase
- ESLINT-01: L7 class component should be written as pure function
- ESLINT-01: L9,10 use destructuring props assignment
- ESLINT-01: L15,16 unexpected single quote usage
- ESLINT-01: L29,30 prop type “object” forbidden
- ESLINT-01: L34 newline required at end of file
- RE-04: Consider destructuring props
- RE-08: Possibly function over class if stateless

Footer.jsx
- ESLINT-01: L4class component should be written as pure function
- ESLINT-01: L21 newline required at end of file
- RE-04: Consider destructuring props
- RE-08: Possibly function over class if stateless

**Comment by yertsti** [comment]
Favorite.jsx
JS-08 Comment on line 7 in Favorite is wrong. No stuff
React-09 Favorite is stateless and should use arrow function instead of class.
Footer.jsx
React-09 Footer should be function instead of class

**Comment by kaihe630** [comment]
Footer.jsx
L 4 and 5 should use stateless components.
Favorite.jsx
L 7 and 8 should use stateless components. 
L 9 and 17 RestaurantInfo doesn’t seem to follow the right naming rule. 

I would change those preferred functions for stateless components.

**Comment by shannonkam** [comment]
Favorites.jsx
- Arch-01
- Design-05 (Line 6, 33)
- REACT-09 (Line 7)

Footer.jsx
- REACT-09 (Line 4) Component is stateless, should use function

**Comment by JeromeWasserman** [comment]
Favorite.jsx
Design-05,07:*Some comments does not reflect whats in the file like having ListStuff.jsx?


Footer.jsx
Design-05,07:*I dont understand what it the Footer
React-09: stateless component

**Comment by GrandeJames** [comment]
Favorite.jsx
L6: Comment is wrong and unnecessary

Footer.jsx
L3: Comment is unnecessary
RE-09: Prefer functions vs classes for stateless components

**Comment by sumidaca** [comment]
Favorites.jsx
L4: REACT-09: Favorite is statless, should be a function
L3: Design-05: Unnecessary comment
L13: ESLINT-01: Parsing error: Unexpected token <

Footer.jsx
L8: ESLINT-01 Parsing error: Unexpected token <

**Comment by jing2003** [comment]
Favorites.jsx
REACT-09: L7 Prefer arrow functions

Footer.jsx
REACT-09: L4 Prefer arrow functions

**Comment by yhanessaanne** [comment]
Favorite.jsx
Design: Forgot to change the comment from the previous template. Must update code to be relevant to the new file’s code.
JS: Line 10: variable “RestaurantInfo” should be camel-cased; must be “restaurantInfo”

Footer.jsx
React: Should be a function instead of a class since it is a stateless component: const Footer = () => {
